const row1 = [
  ["~", "key"],
  ["1", "key"],
  ["2", "key"],
  ["3", "key"],
  ["4", "key"],
  ["5", "key"],
  ["6", "key"],
  ["7", "key"],
  ["8", "key"],
  ["9", "key"],
  ["0", "key"],
  ["-", "key"],
  ["=", "key"],
  ["Backspace", "key backspace"],
];
const row2 = [
  ["Tab", "key tab"],
  ["q", "key"],
  ["w", "key"],
  ["e", "key"],
  ["r", "key"],
  ["t", "key"],
  ["y", "key"],
  ["u", "key"],
  ["i", "key"],
  ["o", "key"],
  ["p", "key"],
  ["[", "key"],
  ["]", "key"],
  ["  ", "key"],
];
const row3 = [
  ["CapsLock", "key capsLock"],
  ["a", "key"],
  ["s", "key"],
  ["d", "key"],
  ["f", "key"],
  ["g", "key"],
  ["h", "key"],
  ["j", "key"],
  ["k", "key"],
  ["l", "key"],
  [";", "key"],
  ["'", "key"],
  ["Enter", "key enter"],
];
const row4 = [
  ["Shift", "key lshift"],
  ["z", "key"],
  ["x", "key"],
  ["c", "key"],
  ["v", "key"],
  ["b", "key"],
  ["n", "key"],
  ["m", "key"],
  [",", "key"],
  [".", "key"],
  ["/", "key"],
  ["Shift", "key rshift"],
];
const row5 = [
  ["Ctrl", "key ctrl"],
  ["Fn", "key fn"],
  ["Win", "key win"],
  ["Alt", "key alt"],
  [" ", "key space"],
  ["Alt", "key alt"],
  ["Ctrl", "key ctrl"],
  ["Home", "key home"],
  ["Arr", "key arr"],
  ["End", "key end"],
];
export const rows = [[...row1], [...row2], [...row3], [...row4], [...row5]];
